// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQpWgOjvxTqL74BJhlmUpCaQ-JS5hd5gY',
    appId: '1:954715702277:web:fd4947f38797c6facb886c',
    messagingSenderId: '954715702277',
    projectId: 'expenseflow-firebase-flutter',
    authDomain: 'expenseflow-firebase-flutter.firebaseapp.com',
    storageBucket: 'expenseflow-firebase-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbSENL8KpgGBw9Uc1vuEQGMt0QP29KrQc',
    appId: '1:954715702277:android:12015b0d009377a6cb886c',
    messagingSenderId: '954715702277',
    projectId: 'expenseflow-firebase-flutter',
    storageBucket: 'expenseflow-firebase-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ILw0Fr1ddEq_90Jx7fkdQ1e-1oY9_YI',
    appId: '1:954715702277:ios:77a13980cb68be2fcb886c',
    messagingSenderId: '954715702277',
    projectId: 'expenseflow-firebase-flutter',
    storageBucket: 'expenseflow-firebase-flutter.firebasestorage.app',
    iosBundleId: 'com.abdulsamad010.expenseflowFirebaseFlutter',
  );
}
